/* 
 * ocrapi
 *
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.OCR.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.OCR.Model
{
    /// <summary>
    /// Result of recognizing a receipt, to extract the key information from the receipt
    /// </summary>
    [DataContract]
    public partial class ReceiptRecognitionResult :  IEquatable<ReceiptRecognitionResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReceiptRecognitionResult" /> class.
        /// </summary>
        /// <param name="Successful">Successful.</param>
        /// <param name="Timestamp">Timestamp.</param>
        /// <param name="BusinessName">BusinessName.</param>
        /// <param name="AddressString">AddressString.</param>
        /// <param name="PhoneNumber">PhoneNumber.</param>
        /// <param name="ReceiptTotal">ReceiptTotal.</param>
        public ReceiptRecognitionResult(bool? Successful = default(bool?), DateTime? Timestamp = default(DateTime?), string BusinessName = default(string), string AddressString = default(string), string PhoneNumber = default(string), double? ReceiptTotal = default(double?))
        {
            this.Successful = Successful;
            this.Timestamp = Timestamp;
            this.BusinessName = BusinessName;
            this.AddressString = AddressString;
            this.PhoneNumber = PhoneNumber;
            this.ReceiptTotal = ReceiptTotal;
        }
        
        /// <summary>
        /// Gets or Sets Successful
        /// </summary>
        [DataMember(Name="Successful", EmitDefaultValue=false)]
        public bool? Successful { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [DataMember(Name="Timestamp", EmitDefaultValue=false)]
        public DateTime? Timestamp { get; set; }

        /// <summary>
        /// Gets or Sets BusinessName
        /// </summary>
        [DataMember(Name="BusinessName", EmitDefaultValue=false)]
        public string BusinessName { get; set; }

        /// <summary>
        /// Gets or Sets AddressString
        /// </summary>
        [DataMember(Name="AddressString", EmitDefaultValue=false)]
        public string AddressString { get; set; }

        /// <summary>
        /// Gets or Sets PhoneNumber
        /// </summary>
        [DataMember(Name="PhoneNumber", EmitDefaultValue=false)]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Gets or Sets ReceiptTotal
        /// </summary>
        [DataMember(Name="ReceiptTotal", EmitDefaultValue=false)]
        public double? ReceiptTotal { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReceiptRecognitionResult {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  BusinessName: ").Append(BusinessName).Append("\n");
            sb.Append("  AddressString: ").Append(AddressString).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("  ReceiptTotal: ").Append(ReceiptTotal).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReceiptRecognitionResult);
        }

        /// <summary>
        /// Returns true if ReceiptRecognitionResult instances are equal
        /// </summary>
        /// <param name="input">Instance of ReceiptRecognitionResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReceiptRecognitionResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Successful == input.Successful ||
                    (this.Successful != null &&
                    this.Successful.Equals(input.Successful))
                ) && 
                (
                    this.Timestamp == input.Timestamp ||
                    (this.Timestamp != null &&
                    this.Timestamp.Equals(input.Timestamp))
                ) && 
                (
                    this.BusinessName == input.BusinessName ||
                    (this.BusinessName != null &&
                    this.BusinessName.Equals(input.BusinessName))
                ) && 
                (
                    this.AddressString == input.AddressString ||
                    (this.AddressString != null &&
                    this.AddressString.Equals(input.AddressString))
                ) && 
                (
                    this.PhoneNumber == input.PhoneNumber ||
                    (this.PhoneNumber != null &&
                    this.PhoneNumber.Equals(input.PhoneNumber))
                ) && 
                (
                    this.ReceiptTotal == input.ReceiptTotal ||
                    (this.ReceiptTotal != null &&
                    this.ReceiptTotal.Equals(input.ReceiptTotal))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Successful != null)
                    hashCode = hashCode * 59 + this.Successful.GetHashCode();
                if (this.Timestamp != null)
                    hashCode = hashCode * 59 + this.Timestamp.GetHashCode();
                if (this.BusinessName != null)
                    hashCode = hashCode * 59 + this.BusinessName.GetHashCode();
                if (this.AddressString != null)
                    hashCode = hashCode * 59 + this.AddressString.GetHashCode();
                if (this.PhoneNumber != null)
                    hashCode = hashCode * 59 + this.PhoneNumber.GetHashCode();
                if (this.ReceiptTotal != null)
                    hashCode = hashCode * 59 + this.ReceiptTotal.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
